spring:
  application:
    name: gorvi ledger
  datasource:
    url: jdbc:postgresql://localhost:5432/gorvi_ledger
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: postgres
    password: postgres
