### Create a new withdrawal for logged in user in account 2
POST http://localhost:8080/api/accounts/2/operations/withdrawals
Content-Type: application/json

{
  "created": "2021-11-28T17:43:00.000Z",
  "currency": "USD",
  "amount": 55,
  "fee": {
    "currency": "USD",
    "amount": 0.55
  },
  "referenceId": "202111281750",
  "notes": "withdrawal of 55",
  "sourceOperationId": null
}

###
